import Head from 'next/head';
import cn from 'classnames';
import styles from '@/styles/NotFound.module.scss';
import StandardButton from '@/components/ui/Button/StandardButton/StandardButton';
import { useRouter } from 'next/router';

function NotFound() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cn(styles['not-found'])}>
        <div className={cn(styles['not-found__content'])}>
          <div className={cn(styles['not-found__titles'])}>
            <h1 className={cn(styles['not-found__title'])}>404</h1>
            <h2 className={cn(styles['not-found__subtitle'])}>Страница не найдена</h2>
          </div>
          <div className={cn(styles['not-found__info'])}>
            <p className={cn(styles['not-found__text'])}>
              Что-то пошло не так. Возможно, страница, которую вы ищете была перемещена, удалена,
              переименована или никогда не существовала.
            </p>
            <StandardButton onClick={() => router.push('/')}>На главную</StandardButton>
          </div>
        </div>
      </main>
    </>
  );
}

export default NotFound;
