'use client';

import cn from 'classnames';
import React, { useEffect } from 'react';
import Sidebar from '@/components/layout/Sidebar/Sidebar';
import Head from 'next/head';
import ProjectService from '@/services/project.service';
import styles from './Projects.module.scss';

export default function ProjectPage() {
  useEffect(() => {
    ProjectService.getProjects().then((data) => console.log(data));
  }, []);

  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={cn(styles.projects)}>
        <Sidebar />

        <main> Project page</main>
      </div>
    </>
  );
}
// dsdeveloper1@digital-sector.ru
// bBQEchjVs7zZGPgp96kTRm
