'use client';

import cn from 'classnames';
import React, { useEffect } from 'react';
import Sidebar from '@/components/layout/Sidebar/Sidebar';
import Head from 'next/head';
import ProjectService from '@/services/project.service';
import Breadcrumb from '@/components/ui/Navigations/Breadcrumb/Breadcrumb';
import styles from './Projects.module.scss';
//------------------------------------------------------------------------

export default function ProjectPage() {
  useEffect(() => {
    ProjectService.getProjects().then((data) => console.log(data));
  }, []);

  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={cn(styles['project-page'])}>
        <div>
          <Sidebar />
        </div>

        <div className={cn(styles.projects)}>
          <div className={cn(styles.projects__breadcrumb)}>
            <ul>
              <li>
                <Breadcrumb href="/" isFirst>
                  Главная
                </Breadcrumb>
              </li>
              <li>
                <Breadcrumb href="/projects" isActive>
                  Проекты
                </Breadcrumb>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
}
// dsdeveloper1@digital-sector.ru
// bBQEchjVs7zZGPgp96kTRm
